[book]
authors = ["basalt-rs"]
language = "en"
title = "Basalt Manual"
description = "Manual for using basalt-rs and corresponding tools"

[build]
create-missing = false

[preprocessor.pagetoc]

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]
git-repository-url = "https://github.com/basalt-rs"

[output.html.print]
enable = false
